# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  scheduler_pod: 'airflow-helm-scheduler-767576bb4c-r2plw -c scheduler'

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: echo Hello, world2!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    - task: oc-cmd@2
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'Openshift'
        cmd: 'exec airflow-helm-scheduler-767576bb4c-r2plw -c scheduler -- ls -l /opt/airflow/dags'
  displayName: 'Run a multi-line script'
